# Generated by Django 3.2.6 on 2021-09-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0003_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.IntegerField(null=True),
        ),
    ]
