# Generated by Django 3.2.6 on 2021-12-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0005_emailcontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='img',
            field=models.ImageField(default=3, upload_to='', verbose_name='foto'),
            preserve_default=False,
        ),
    ]
