# Generated by Django 3.2.6 on 2021-12-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0006_produto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.CharField(choices=[('ativo', 'ativo'), ('inativo', 'inativo')], default='ativo', max_length=15),
            preserve_default=False,
        ),
    ]
