# Generated by Django 3.2.6 on 2021-12-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_id', models.IntegerField()),
                ('motivo', models.TextField()),
            ],
        ),
    ]
